name = "quadpack"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran QUADPACK"
homepage = "https://github.com/jacobwilliams/quadpack"
keywords = ["quadrature"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"
include-dir = "src"

[install]
library = true
