name = "quadpack"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran QUADPACK"
homepage = "https://github.com/jacobwilliams/quadpack"
keywords = ["quadrature"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "double"
source-dir = "test"
main = "quadpack_tests_double.F90"

[[test]]
name = "single"
source-dir = "test"
main = "quadpack_tests_single.F90"
